openapi: 3.2.0
info:
  title: PlantPredict Version API
  description: The HTTP API used by the PlantPredict web application. This API can also be accessed directly
    by having your Company Admin generate API credentials. If you do not know your Company Admin, contact
    support@plantpredict.com for assistance.
  contact:
    name: PlantPredict Support
    url: https://plantpredict.com/contact/
    email: support@plantpredict.com
  version: current
security:
- Bearer: []
tags:
- name: Version
paths:
  /Version:
    get:
      tags:
      - Version
      summary: Get the system version.
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/PlantPredict.Entities.DTO.VersionInfo'
            application/json:
              schema:
                $ref: '#/components/schemas/PlantPredict.Entities.DTO.VersionInfo'
            text/json:
              schema:
                $ref: '#/components/schemas/PlantPredict.Entities.DTO.VersionInfo'
components:
  schemas:
    PlantPredict.Entities.DTO.VersionInfo:
      type: object
      properties:
        version:
          type:
          - string
          - 'null'
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: 'JWT Authorization header using the Bearer scheme. Example: "Authorization: Bearer
        {token}"'
      name: Authorization
      in: header
